force-app/main/default/objects/Access_Management_Settings__c/Access_Management_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores runtime configurations for Persona Access Framework.</description>
    <label>Access Management Settings</label>
</CustomObject>

force-app/main/default/objects/Access_Management_Settings__c/fields/Enable_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Toggle trigger execution for Persona Access Framework based triggers</description>
    <label>Enable Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Persona_Access_Mapping__mdt/Persona_Access_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Stores mappings between Personas and their associated permissions/groups.</description>
    <label>Persona Access Mapping</label>
    <pluralLabel>Persona Access Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Persona_Access_Mapping__mdt/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elevated User</fullName>
                <default>true</default>
                <label>Elevated User</label>
            </value>
            <value>
                <fullName>Read-Edit User</fullName>
            </value>
            <value>
                <fullName>Read-Only User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Persona_Access_Mapping__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Access assignment</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <default>true</default>
                <label>Group</label>
            </value>
            <value>
                <fullName>PermissionSet</fullName>
            </value>
            <value>
                <fullName>PermissionSetGroup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <description>The persona associated with the user</description>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Persona</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Persona.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Elevated User</fullName>
    </customValue>
    <customValue>
        <fullName>Read-Edit User</fullName>
    </customValue>
    <customValue>
        <fullName>Read-Only User</fullName>
    </customValue>
    <description>User Personas available for current Org</description>
    <masterLabel>Persona</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UserAccessTriggerHelper.cls
public with sharing class UserAccessTriggerHelper {
    public static void handleAfterInsert(List<User> newUsers) {
        try {
            if (Access_Management_Settings__c.getInstance().Enable_Trigger__c) {
                List<User> usersWithNoPersona = new List<User>();
                Map<String, List<User>> usersForPersona = new Map<String, List<User>>();

                //iterating over list of new users and segrating them based on persona into a Map and the ones with no persona in a separate List
                for (User u : newUsers) {
                    if (u.Persona__c == null) {
                        usersWithNoPersona.add(u);
                    } else {
                        if (!usersForPersona.containsKey(u.Persona__c)) {
                            usersForPersona.put(u.Persona__c, new List<User>());
                        }
                        usersForPersona.get(u.Persona__c).add(u);
                    }
                }

                //fetching all Persona Access Mapping records for the personas of new Users
                List<Persona_Access_Mapping__mdt> personaAccessMappings = new List<Persona_Access_Mapping__mdt>();
                personaAccessMappings = [
                    SELECT Persona__c, Type__c, API_Names__c
                    FROM Persona_Access_Mapping__mdt
                    WHERE
                        Persona__c IN :usersForPersona.keySet()
                    WITH USER_MODE
                ];

                List<Persona_Access_Mapping__mdt> personaPermissionSetGroups = new List<Persona_Access_Mapping__mdt>();
                List<Persona_Access_Mapping__mdt> personaPermissionSets = new List<Persona_Access_Mapping__mdt>();
                List<Persona_Access_Mapping__mdt> personaGroups = new List<Persona_Access_Mapping__mdt>();

                for(Persona_Access_Mapping__mdt pac : personaAccessMappings){
                    if(pac.Type__c == 'PermissionSetGroup'){
                        personaPermissionSetGroups.add(pac);
                    }else if(pac.Type__c == 'PermissionSet'){
                        personaPermissionSets.add(pac);
                    }else if(pac.Type__c == 'Group'){
                        personaGroups.add(pac);
                    }
                }

            }
        } catch (Exception ex) {
            System.debug('Error handling access for persona');
        }
    }

    public static void assignPermissionSetGroups(Map<String, List<User>> usersForPersona, List<Persona_Access_Mapping__mdt> personaPermissionSetGroups){
        Map<String, List<String>> permissionSetGroupsForPersona = new Map<String, List<String>>();
        for(Persona_Access_Mapping__mdt pam : personaPermissionSetGroups){
            permissionSetGroupsForPersona.add(pam.Persona__c, pam.API_Names__c.split(','));
        }

        List<PermissionSetGroup> permissionSetGroups = new List<PermissionSetGroup>();
        permissionSetGroups = [SELECT Id, DeveloperName FROM PermissionSetGroup WHERE DeveloperName IN :permissionSetGroupsForPersona.values()];
    }
}